from airflow import DAG
from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.models import Variable
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
#from airflow.sensors.filesystem import FileSensor
from airflow.sensors.base import BaseSensorOperator
from datetime import datetime, timedelta
import logging
from decimal import Decimal
import json
from io import StringIO
from airflow.providers.google.cloud.sensors.gcs import GCSObjectExistenceSensor
from airflow.providers.google.cloud.sensors.gcs import GCSHook # <-- AGREGAR ESTA IMPORTACION
from airflow.providers.google.cloud.hooks.gcs import GCSHook
import time
import os
import tempfile



logger = logging.getLogger(__name__)

def serialize_value(value):
    """
    Helper para serializar valores de PostgreSQL a JSON.
    Convierte Decimal, date, datetime a string para preservar precisión.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value  # Ya es string
    if isinstance(value, datetime):
        return value.isoformat()  # Formato ISO 8601
    if isinstance(value, (int, float, Decimal)):
        return str(value)  # Tipos numericos
    return json.dumps(value)  # Otros tipos

def get_variable(key, default_var=""):
    """
    Helper para obtener variables de Airflow y deserializarlas.
    Retorna el valor como string (compatible con SQL queries).
    
    Para conversiones específicas:
    - int: int(get_variable('key'))
    - Decimal: Decimal(get_variable('key'))
    - datetime: datetime.fromisoformat(get_variable('key'))
    """
    raw = Variable.get(key, default_var=default_var)
    try:
        return json.loads(raw)
    except Exception:
        return raw
### FUNCIONES DE CADA TAREA ###

def FileAT(**kwargs):
    value = 'AT10'
    Variable.set('FileAT', serialize_value(value))

def FileCodSupervisado(**kwargs):
    value = '01410'
    Variable.set('FileCodSupervisado', serialize_value(value))

def FechaFile(**kwargs):
    hook = PostgresHook(postgres_conn_id='repodataprd')
    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')
    sql_query = '''SELECT TO_CHAR(DATE_TRUNC('month', CURRENT_DATE - INTERVAL '28 days') + INTERVAL '1 month - 1 day', 'yymmdd');'''
    result = hook.get_records(sql_query)
    # Variable.set('FechaFile', serialize_value(result[0][0]))
    Variable.set('FechaFile', "250630")  # <-- CAMBIO TEMPORAL PARA PRUEBAS (usamos fecha del 30 de Junio 2025) SE DEBE CAMBIAR LUEGO
    print(f"Value of FechaFile: {get_variable('FechaFile')}")

def AT10_FileName_LA(**kwargs):
    hook = PostgresHook(postgres_conn_id='repodataprd')
    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')
    sql_query = '''SELECT CONCAT(CONCAT(CONCAT('#ODI_AT_SUDEBAN_DEV.FileAT','#ODI_AT_SUDEBAN_DEV.FileCodSupervisado'),'#ODI_AT_SUDEBAN_DEV.FechaFile'),'_LA.txt');'''
    result = hook.get_records(sql_query)
    Variable.set('AT10_FileName_LA', serialize_value(result[0][0]))

def AT10_FileName_Fideicomiso(**kwargs):
    hook = PostgresHook(postgres_conn_id='repodataprd')
    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')
    sql_query = '''SELECT CONCAT(CONCAT(CONCAT('#ODI_AT_SUDEBAN_DEV.FileAT','#ODI_AT_SUDEBAN_DEV.FileCodSupervisado'),'#ODI_AT_SUDEBAN_DEV.FechaFile'),'_FIDEICOMISO.txt')'''
    result = hook.get_records(sql_query)
    Variable.set('AT10_FileName_Fideicomiso', serialize_value(result[0][0]))

def AT10_UNION(**kwargs):

    # Obtener variables
    FileAT = get_variable('FileAT')
    FileCodSupervisado = get_variable('FileCodSupervisado')
    FechaFile = get_variable('FechaFile')

    # Define la informacion del bucket y el objeto en GCS
    gcs_bucket = 'airflow-dags-data'
    gcs_object_fideicomiso = f'data/AT10/UNIFICADO/{FileAT}{FileCodSupervisado}{FechaFile}_FIDEICOMISO.txt'
    gcs_object_la = f'data/AT10/UNIFICADO/{FileAT}{FileCodSupervisado}{FechaFile}_LA.txt'

    #Inicializa los hooks
    hook = PostgresHook(postgres_conn_id='repodataprd')
    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')

	#Crea tabla si no existe
    hook.run('''
        CREATE TABLE IF NOT EXISTS ATSUDEBAN.ATS_TH_AT10 (
		OFICINA	VARCHAR(10),
		CODINSTRUMENTO	VARCHAR(20),
		TIPOSISTEMA	VARCHAR(10),
		CODCTACONTABLE	VARCHAR(20),
		IDINSTRUMENTO	VARCHAR(10),
		CODEMISOR	VARCHAR(10),
		PAISEMISOR	VARCHAR(10),
		CODCUSTODIO	VARCHAR(10),
		PAISCUSTODIO	VARCHAR(10),
		EMPRESARIESGOCUSTODIO	VARCHAR(200),
		CALIFRIESGOCUSTODIO	VARCHAR(20),
		MONEDA	VARCHAR(10),
		FECHAEMISION	VARCHAR(8),
		FECHAADQUISICION	VARCHAR(8),
		FECHAVCTO	VARCHAR(8),
		ULTFECHATRANS	VARCHAR(8),
		NROTRANSFERENCIAS	VARCHAR(100),
		VALORNOMINAL	NUMERIC(30,8),
		COSTOADQUISICION	NUMERIC(30,8),
		VALORMERCADOTRANS	NUMERIC(30,2),
		PORCENTAJECOMPRA	NUMERIC(30,8),
		PORCENTAJEVALORMERCADO	NUMERIC(30,8),
		VALORMERCADO	NUMERIC(30,8),
		VALORPRESENTE	NUMERIC(30,8),
		TIPOCAMBIOCOMPRA	NUMERIC(30,8),
		TIPOCAMBIOCIERRE	NUMERIC(30,8),
		GANOPERDIFCAMBIARIO	NUMERIC(30,2),
		GANOPERDNOREALIZADA	NUMERIC(30,8),
		PRIMAODESCUENTO	NUMERIC(30,8),
		COSTOAMORTIZADO	NUMERIC(30,8),
		VALORENLIBROS	NUMERIC(30,8),
		TASADESCTO	NUMERIC(10,4),
		NROACCIONES	VARCHAR(30),
		PRECIOMERCADOACCIONES	NUMERIC(30,2),
		PARTCPATRIMONIAL	NUMERIC(30,4),
		MONTOPROVISION	NUMERIC(30,2),
		NRODECRETO	VARCHAR(100),
		NROEMISION	VARCHAR(100),
		SERIEINSTR	VARCHAR(100),
		TASAINTCUPON	NUMERIC(10,4),
		TASAINTERESES	NUMERIC(10,4),
		FECHAINICIOCP	VARCHAR(8),
		FECHAVTOCP	VARCHAR(8),
		INTERESESCOBRADOS	NUMERIC(30,2),
		INTERESESDEVENGADOS	NUMERIC(30,2),
		DIVIDENDOSCOBRADOS	NUMERIC(30,2),
		RENDPORCOBRAR	NUMERIC(30,2),
		PERIOPAGOINT	VARCHAR(30),
		FECHACOBRO	VARCHAR(8),
		DIVDECRNOCOBRADOS	NUMERIC(30,2),
		CTACBLEORITRANS	VARCHAR(30),
		MONTOCANJE	NUMERIC(30,2),
		FECHACANJE	VARCHAR(8),
		CONTRAPARTECANJE	VARCHAR(100),
		CODINSTRENTREGADO	VARCHAR(15),
		PATRIEMPRESA	NUMERIC(30,2),
		FECHAEDOFINANCIERO	VARCHAR(8),
		MONTOCAPSOCIAL	NUMERIC(30,2),
		NROACCIONESCIRC	NUMERIC(30,2),
		CANTIDADACCIONES	NUMERIC(30),
		ACTIVOSUBYACENTE	NUMERIC(30),
		VALORNOMACTIVO	NUMERIC(30,2),
		MONEDAACTIVO	VARCHAR(10),
		TIPOCAMCIERRESUB	NUMERIC(10,4),
		CODEMISORSUB	VARCHAR(10),
		CODCUSTODIOSUB	VARCHAR(10),
		TASACUPONSUB	NUMERIC(10,4),
		FECHAVCTOSUB	VARCHAR(8),
		RESULTADONETO	NUMERIC(30,2),
		GANOPERPARTPATRIM	NUMERIC(30,2),
		BASECALCULO	VARCHAR(30),
		PORCION	VARCHAR(30)
	);
    ''')

	# Vaciamos la tabla para no duplicar datos.
    hook.run("TRUNCATE TABLE ATSUDEBAN.ATS_TH_AT10;")

    # CARGA PORCIÓN DE FIDEICOMISO
    temp_dir = tempfile.mkdtemp()
    local_file_path_fideicomiso = os.path.join(temp_dir, f'{FileAT}{FileCodSupervisado}{FechaFile}_FIDEICOMISO.txt')
    gcs_hook.download(
        bucket_name=gcs_bucket,
        object_name=gcs_object_fideicomiso,
        filename=local_file_path_fideicomiso
    )

    temp_sql = """
        CREATE TEMP TABLE temp_at10_union_fideicomiso (
			OFICINA	VARCHAR(10),
			CODINSTRUMENTO	VARCHAR(20),
			TIPOSISTEMA	VARCHAR(10),
			CODCTACONTABLE	VARCHAR(20),
			IDINSTRUMENTO	VARCHAR(10),
			CODEMISOR	VARCHAR(10),
			PAISEMISOR	VARCHAR(10),
			CODCUSTODIO	VARCHAR(10),
			PAISCUSTODIO	VARCHAR(10),
			EMPRESARIESGOCUSTODIO	VARCHAR(200),
			CALIFRIESGOCUSTODIO	VARCHAR(20),
			MONEDA	VARCHAR(10),
			FECHAEMISION	VARCHAR(8),
			FECHAADQUISICION	VARCHAR(8),
			FECHAVCTO	VARCHAR(8),
			ULTFECHATRANS	VARCHAR(8),
			NROTRANSFERENCIAS	VARCHAR(100),
			VALORNOMINAL	VARCHAR(100),
			COSTOADQUISICION	VARCHAR(100),
			VALORMERCADOTRANS	VARCHAR(100),
			PORCENTAJECOMPRA	VARCHAR(100),
			PORCENTAJEVALORMERCADO	VARCHAR(100),
			VALORMERCADO	VARCHAR(100),
			VALORPRESENTE	VARCHAR(100),
			TIPOCAMBIOCOMPRA	VARCHAR(100),
			TIPOCAMBIOCIERRE	VARCHAR(100),
			GANOPERDIFCAMBIARIO	VARCHAR(100),
			GANOPERDNOREALIZADA	VARCHAR(100),
			PRIMAODESCUENTO	VARCHAR(100),
			COSTOAMORTIZADO	VARCHAR(100),
			VALORENLIBROS	VARCHAR(100),
			TASADESCTO	VARCHAR(50),
			NROACCIONES	VARCHAR(30),
			PRECIOMERCADOACCIONES	VARCHAR(100),
			PARTCPATRIMONIAL	VARCHAR(100),
			MONTOPROVISION	VARCHAR(100),
			NRODECRETO	VARCHAR(100),
			NROEMISION	VARCHAR(100),
			SERIEINSTR	VARCHAR(100),
			TASAINTCUPON	VARCHAR(100),
			TASAINTERESES	VARCHAR(100),
			FECHAINICIOCP	VARCHAR(8),
			FECHAVTOCP	VARCHAR(8),
			INTERESESCOBRADOS	VARCHAR(100),
			INTERESESDEVENGADOS	VARCHAR(100),
			DIVIDENDOSCOBRADOS	VARCHAR(100),
			RENDPORCOBRAR	VARCHAR(100),
			PERIOPAGOINT	VARCHAR(30),
			FECHACOBRO	VARCHAR(8),
			DIVDECRNOCOBRADOS	VARCHAR(100),
			CTACBLEORITRANS	VARCHAR(30),
			MONTOCANJE	VARCHAR(100),
			FECHACANJE	VARCHAR(8),
			CONTRAPARTECANJE	VARCHAR(100),
			CODINSTRENTREGADO	VARCHAR(15),
			PATRIEMPRESA	VARCHAR(100),
			FECHAEDOFINANCIERO	VARCHAR(8),
			MONTOCAPSOCIAL	VARCHAR(100),
			NROACCIONESCIRC	VARCHAR(100),
			CANTIDADACCIONES	NUMERIC(30),
			ACTIVOSUBYACENTE	NUMERIC(30),
			VALORNOMACTIVO	VARCHAR(100),
			MONEDAACTIVO	VARCHAR(10),
			TIPOCAMCIERRESUB	VARCHAR(50),
			CODEMISORSUB	VARCHAR(10),
			CODCUSTODIOSUB	VARCHAR(10),
			TASACUPONSUB	VARCHAR(50),
			FECHAVCTOSUB	VARCHAR(8),
			RESULTADONETO	VARCHAR(100),
			GANOPERPARTPATRIM	VARCHAR(100),
			BASECALCULO	VARCHAR(30)
        );
        COPY temp_at10_union_fideicomiso FROM STDIN WITH (FORMAT TEXT, HEADER false, DELIMITER '~');
        INSERT INTO ATSUDEBAN.ATS_TH_AT10 (
			OFICINA,
			CODINSTRUMENTO,
			TIPOSISTEMA,
			CODCTACONTABLE,
			IDINSTRUMENTO,
			CODEMISOR,
			PAISEMISOR,
			CODCUSTODIO,
			PAISCUSTODIO,
			EMPRESARIESGOCUSTODIO,
			CALIFRIESGOCUSTODIO,
			MONEDA,
			FECHAEMISION,
			FECHAADQUISICION,
			FECHAVCTO,
			ULTFECHATRANS,
			NROTRANSFERENCIAS,
			VALORNOMINAL,
			COSTOADQUISICION,
			VALORMERCADOTRANS,
			PORCENTAJECOMPRA,
			PORCENTAJEVALORMERCADO,
			VALORMERCADO,
			VALORPRESENTE,
			TIPOCAMBIOCOMPRA,
			TIPOCAMBIOCIERRE,
			GANOPERDIFCAMBIARIO,
			GANOPERDNOREALIZADA,
			PRIMAODESCUENTO,
			COSTOAMORTIZADO,
			VALORENLIBROS,
			TASADESCTO,
			NROACCIONES,
			PRECIOMERCADOACCIONES,
			PARTCPATRIMONIAL,
			MONTOPROVISION,
			NRODECRETO,
			NROEMISION,
			SERIEINSTR,
			TASAINTCUPON,
			TASAINTERESES,
			FECHAINICIOCP,
			FECHAVTOCP,
			INTERESESCOBRADOS,
			INTERESESDEVENGADOS,
			DIVIDENDOSCOBRADOS,
			RENDPORCOBRAR,
			PERIOPAGOINT,
			FECHACOBRO,
			DIVDECRNOCOBRADOS,
			CTACBLEORITRANS,
			MONTOCANJE,
			FECHACANJE,
			CONTRAPARTECANJE,
			CODINSTRENTREGADO,
			PATRIEMPRESA,
			FECHAEDOFINANCIERO,
			MONTOCAPSOCIAL,
			NROACCIONESCIRC,
			CANTIDADACCIONES,
			ACTIVOSUBYACENTE,
			VALORNOMACTIVO,
			MONEDAACTIVO,
			TIPOCAMCIERRESUB,
			CODEMISORSUB,
			CODCUSTODIOSUB,
			TASACUPONSUB,
			FECHAVCTOSUB,
			RESULTADONETO,
			GANOPERPARTPATRIM,
			BASECALCULO,
			PORCION
        )
        SELECT
			OFICINA AS OFICINA,
			CODINSTRUMENTO AS CODINSTRUMENTO,
			TIPOSISTEMA AS TIPOSISTEMA,
			CODCTACONTABLE AS CODCTACONTABLE,
			IDINSTRUMENTO AS IDINSTRUMENTO,
			CODEMISOR AS CODEMISOR,
			PAISEMISOR AS PAISEMISOR,
			CODCUSTODIO AS CODCUSTODIO,
			PAISCUSTODIO AS PAISCUSTODIO,
			EMPRESARIESGOCUSTODIO AS EMPRESARIESGOCUSTODIO,
			CALIFRIESGOCUSTODIO AS CALIFRIESGOCUSTODIO,
			MONEDA AS MONEDA,
			FECHAEMISION AS FECHAEMISION,
			FECHAADQUISICION AS FECHAADQUISICION,
			FECHAVCTO AS FECHAVCTO,
			ULTFECHATRANS AS ULTFECHATRANS,
			NROTRANSFERENCIAS AS NROTRANSFERENCIAS,
			CAST(REPLACE(VALORNOMINAL, ',', '.') AS DECIMAL) AS VALORNOMINAL,
			CAST(REPLACE(COSTOADQUISICION, ',', '.') AS DECIMAL) AS COSTOADQUISICION,
			CAST(REPLACE(VALORMERCADOTRANS, ',', '.') AS DECIMAL) AS VALORMERCADOTRANS,
			CAST(REPLACE(PORCENTAJECOMPRA, ',', '.') AS DECIMAL) AS PORCENTAJECOMPRA,
			CAST(REPLACE(PORCENTAJEVALORMERCADO, ',', '.') AS DECIMAL) AS PORCENTAJEVALORMERCADO,
			CAST(REPLACE(VALORMERCADO, ',', '.') AS DECIMAL) AS VALORMERCADO,
			CAST(REPLACE(VALORPRESENTE, ',', '.') AS DECIMAL) AS VALORPRESENTE,
			CAST(REPLACE(TIPOCAMBIOCOMPRA, ',', '.') AS DECIMAL) AS TIPOCAMBIOCOMPRA,
			CAST(REPLACE(TIPOCAMBIOCIERRE, ',', '.') AS DECIMAL) AS TIPOCAMBIOCIERRE,
			CAST(REPLACE(GANOPERDIFCAMBIARIO, ',', '.') AS DECIMAL) AS GANOPERDIFCAMBIARIO,
			CAST(REPLACE(GANOPERDNOREALIZADA, ',', '.') AS DECIMAL) AS GANOPERDNOREALIZADA,
			CAST(REPLACE(PRIMAODESCUENTO, ',', '.') AS DECIMAL) AS PRIMAODESCUENTO,
			CAST(REPLACE(COSTOAMORTIZADO, ',', '.') AS DECIMAL) AS COSTOAMORTIZADO,
			CAST(REPLACE(VALORENLIBROS, ',', '.') AS DECIMAL) AS VALORENLIBROS,
			CAST(REPLACE(TASADESCTO, ',', '.') AS DECIMAL) AS TASADESCTO,
			NROACCIONES AS NROACCIONES,
			CAST(REPLACE(PRECIOMERCADOACCIONES, ',', '.') AS DECIMAL) AS PRECIOMERCADOACCIONES,
			CAST(REPLACE(PARTCPATRIMONIAL, ',', '.') AS DECIMAL) AS PARTCPATRIMONIAL,
			CAST(REPLACE(MONTOPROVISION, ',', '.') AS DECIMAL) AS MONTOPROVISION,
			NRODECRETO AS NRODECRETO,
			NROEMISION AS NROEMISION,
			SERIEINSTR AS SERIEINSTR,
			CAST(REPLACE(TASAINTCUPON, ',', '.') AS DECIMAL) AS TASAINTCUPON,
			CAST(REPLACE(TASAINTERESES, ',', '.') AS DECIMAL) AS TASAINTERESES,
			FECHAINICIOCP AS FECHAINICIOCP,
			FECHAVTOCP AS FECHAVTOCP,
			CAST(REPLACE(INTERESESCOBRADOS, ',', '.') AS DECIMAL) AS INTERESESCOBRADOS,
			CAST(REPLACE(INTERESESDEVENGADOS, ',', '.') AS DECIMAL) AS INTERESESDEVENGADOS,
			CAST(REPLACE(DIVIDENDOSCOBRADOS, ',', '.') AS DECIMAL) AS DIVIDENDOSCOBRADOS,
			CAST(REPLACE(RENDPORCOBRAR, ',', '.') AS DECIMAL) AS RENDPORCOBRAR,
			PERIOPAGOINT AS PERIOPAGOINT,
			FECHACOBRO AS FECHACOBRO,
			CAST(REPLACE(DIVDECRNOCOBRADOS, ',', '.') AS DECIMAL) AS DIVDECRNOCOBRADOS,
			CTACBLEORITRANS AS CTACBLEORITRANS,
			CAST(REPLACE(MONTOCANJE, ',', '.') AS DECIMAL) AS MONTOCANJE,
			FECHACANJE AS FECHACANJE,
			CONTRAPARTECANJE AS CONTRAPARTECANJE,
			CODINSTRENTREGADO AS CODINSTRENTREGADO,
			CAST(REPLACE(PATRIEMPRESA, ',', '.') AS DECIMAL) AS PATRIEMPRESA,
			FECHAEDOFINANCIERO AS FECHAEDOFINANCIERO,
			CAST(REPLACE(MONTOCAPSOCIAL, ',', '.') AS DECIMAL) AS MONTOCAPSOCIAL,
			CAST(REPLACE(NROACCIONESCIRC, ',', '.') AS DECIMAL) AS NROACCIONESCIRC,
			CAST(CANTIDADACCIONES AS NUMERIC) AS CANTIDADACCIONES,
			CAST(ACTIVOSUBYACENTE AS NUMERIC) AS ACTIVOSUBYACENTE,
			CAST(REPLACE(VALORNOMACTIVO, ',', '.') AS DECIMAL) AS VALORNOMACTIVO,
			MONEDAACTIVO AS MONEDAACTIVO,
			CAST(REPLACE(TIPOCAMCIERRESUB, ',', '.') AS DECIMAL) AS TIPOCAMCIERRESUB,
			CODEMISORSUB AS CODEMISORSUB,
			CODCUSTODIOSUB AS CODCUSTODIOSUB,
			CAST(REPLACE(TASACUPONSUB, ',', '.') AS DECIMAL) AS TASACUPONSUB,
			FECHAVCTOSUB AS FECHAVCTOSUB,
			CAST(REPLACE(RESULTADONETO, ',', '.') AS DECIMAL) AS RESULTADONETO,
			CAST(REPLACE(GANOPERPARTPATRIM, ',', '.') AS DECIMAL) AS GANOPERPARTPATRIM,
			TRIM(BASECALCULO) AS BASECALCULO,
			'FIDEICOMISO' AS PORCION
        FROM temp_at10_union_fideicomiso;
    """
    hook.copy_expert(sql=temp_sql, filename=local_file_path_fideicomiso)
    os.remove(local_file_path_fideicomiso)
    os.rmdir(temp_dir)

	# CARGA PORCIÓN DE LA
    temp_dir = tempfile.mkdtemp()
    local_file_path_la = os.path.join(temp_dir, f'{FileAT}{FileCodSupervisado}{FechaFile}_LA.txt')
    gcs_hook.download(
        bucket_name=gcs_bucket,
        object_name=gcs_object_la,
        filename=local_file_path_la
    )

    temp_sql = """
        CREATE TEMP TABLE temp_at10_union_la (
			OFICINA	VARCHAR(10),
			CODINSTRUMENTO	VARCHAR(20),
			TIPOSISTEMA	VARCHAR(10),
			CODCTACONTABLE	VARCHAR(20),
			IDINSTRUMENTO	VARCHAR(10),
			CODEMISOR	VARCHAR(10),
			PAISEMISOR	VARCHAR(10),
			CODCUSTODIO	VARCHAR(10),
			PAISCUSTODIO	VARCHAR(10),
			EMPRESARIESGOCUSTODIO	VARCHAR(200),
			CALIFRIESGOCUSTODIO	VARCHAR(20),
			MONEDA	VARCHAR(10),
			FECHAEMISION	VARCHAR(8),
			FECHAADQUISICION	VARCHAR(8),
			FECHAVCTO	VARCHAR(8),
			ULTFECHATRANS	VARCHAR(8),
			NROTRANSFERENCIAS	VARCHAR(100),
			VALORNOMINAL	VARCHAR(100),
			COSTOADQUISICION	VARCHAR(100),
			VALORMERCADOTRANS	VARCHAR(100),
			PORCENTAJECOMPRA	VARCHAR(100),
			PORCENTAJEVALORMERCADO	VARCHAR(100),
			VALORMERCADO	VARCHAR(100),
			VALORPRESENTE	VARCHAR(100),
			TIPOCAMBIOCOMPRA	VARCHAR(100),
			TIPOCAMBIOCIERRE	VARCHAR(100),
			GANOPERDIFCAMBIARIO	VARCHAR(100),
			GANOPERDNOREALIZADA	VARCHAR(100),
			PRIMAODESCUENTO	VARCHAR(100),
			COSTOAMORTIZADO	VARCHAR(100),
			VALORENLIBROS	VARCHAR(100),
			TASADESCTO	VARCHAR(50),
			NROACCIONES	VARCHAR(30),
			PRECIOMERCADOACCIONES	VARCHAR(100),
			PARTCPATRIMONIAL	VARCHAR(100),
			MONTOPROVISION	VARCHAR(100),
			NRODECRETO	VARCHAR(100),
			NROEMISION	VARCHAR(100),
			SERIEINSTR	VARCHAR(100),
			TASAINTCUPON	VARCHAR(50),
			TASAINTERESES	VARCHAR(50),
			FECHAINICIOCP	VARCHAR(8),
			FECHAVTOCP	VARCHAR(8),
			INTERESESCOBRADOS	VARCHAR(100),
			INTERESESDEVENGADOS	VARCHAR(100),
			DIVIDENDOSCOBRADOS	VARCHAR(100),
			RENDPORCOBRAR	VARCHAR(100),
			PERIOPAGOINT	VARCHAR(30),
			FECHACOBRO	VARCHAR(8),
			DIVDECRNOCOBRADOS	VARCHAR(100),
			CTACBLEORITRANS	VARCHAR(30),
			MONTOCANJE	VARCHAR(100),
			FECHACANJE	VARCHAR(8),
			CONTRAPARTECANJE	VARCHAR(100),
			CODINSTRENTREGADO	VARCHAR(15),
			PATRIEMPRESA	VARCHAR(100),
			FECHAEDOFINANCIERO	VARCHAR(8),
			MONTOCAPSOCIAL	VARCHAR(100),
			NROACCIONESCIRC	VARCHAR(100),
			CANTIDADACCIONES	NUMERIC(30),
			ACTIVOSUBYACENTE	NUMERIC(30),
			VALORNOMACTIVO	VARCHAR(100),
			MONEDAACTIVO	VARCHAR(10),
			TIPOCAMCIERRESUB	VARCHAR(50),
			CODEMISORSUB	VARCHAR(10),
			CODCUSTODIOSUB	VARCHAR(10),
			TASACUPONSUB	VARCHAR(50),
			FECHAVCTOSUB	VARCHAR(8),
			RESULTADONETO	VARCHAR(100),
			GANOPERPARTPATRIM	VARCHAR(100),
			BASECALCULO	VARCHAR(30)
        );
        COPY temp_at10_union_la FROM STDIN WITH (FORMAT TEXT, HEADER false, DELIMITER '~');
        INSERT INTO ATSUDEBAN.ATS_TH_AT10 (
			OFICINA,
			CODINSTRUMENTO,
			TIPOSISTEMA,
			CODCTACONTABLE,
			IDINSTRUMENTO,
			CODEMISOR,
			PAISEMISOR,
			CODCUSTODIO,
			PAISCUSTODIO,
			EMPRESARIESGOCUSTODIO,
			CALIFRIESGOCUSTODIO,
			MONEDA,
			FECHAEMISION,
			FECHAADQUISICION,
			FECHAVCTO,
			ULTFECHATRANS,
			NROTRANSFERENCIAS,
			VALORNOMINAL,
			COSTOADQUISICION,
			VALORMERCADOTRANS,
			PORCENTAJECOMPRA,
			PORCENTAJEVALORMERCADO,
			VALORMERCADO,
			VALORPRESENTE,
			TIPOCAMBIOCOMPRA,
			TIPOCAMBIOCIERRE,
			GANOPERDIFCAMBIARIO,
			GANOPERDNOREALIZADA,
			PRIMAODESCUENTO,
			COSTOAMORTIZADO,
			VALORENLIBROS,
			TASADESCTO,
			NROACCIONES,
			PRECIOMERCADOACCIONES,
			PARTCPATRIMONIAL,
			MONTOPROVISION,
			NRODECRETO,
			NROEMISION,
			SERIEINSTR,
			TASAINTCUPON,
			TASAINTERESES,
			FECHAINICIOCP,
			FECHAVTOCP,
			INTERESESCOBRADOS,
			INTERESESDEVENGADOS,
			DIVIDENDOSCOBRADOS,
			RENDPORCOBRAR,
			PERIOPAGOINT,
			FECHACOBRO,
			DIVDECRNOCOBRADOS,
			CTACBLEORITRANS,
			MONTOCANJE,
			FECHACANJE,
			CONTRAPARTECANJE,
			CODINSTRENTREGADO,
			PATRIEMPRESA,
			FECHAEDOFINANCIERO,
			MONTOCAPSOCIAL,
			NROACCIONESCIRC,
			CANTIDADACCIONES,
			ACTIVOSUBYACENTE,
			VALORNOMACTIVO,
			MONEDAACTIVO,
			TIPOCAMCIERRESUB,
			CODEMISORSUB,
			CODCUSTODIOSUB,
			TASACUPONSUB,
			FECHAVCTOSUB,
			RESULTADONETO,
			GANOPERPARTPATRIM,
			BASECALCULO,
			PORCION
        )
        SELECT
			OFICINA,
			CODINSTRUMENTO,
			TIPOSISTEMA,
			CODCTACONTABLE,
			IDINSTRUMENTO,
			CODEMISOR,
			PAISEMISOR,
			CODCUSTODIO,
			PAISCUSTODIO,
			EMPRESARIESGOCUSTODIO,
			CALIFRIESGOCUSTODIO,
			MONEDA,
			FECHAEMISION,
			FECHAADQUISICION,
			FECHAVCTO,
			ULTFECHATRANS,
			NROTRANSFERENCIAS,
			CAST(REPLACE(VALORNOMINAL, ',', '.') AS DECIMAL) AS VALORNOMINAL,
			CAST(REPLACE(COSTOADQUISICION, ',', '.') AS DECIMAL) AS COSTOADQUISICION,
			CAST(REPLACE(VALORMERCADOTRANS, ',', '.') AS DECIMAL) AS VALORMERCADOTRANS,
			CAST(REPLACE(PORCENTAJECOMPRA, ',', '.') AS DECIMAL) AS PORCENTAJECOMPRA,
			CAST(REPLACE(PORCENTAJEVALORMERCADO, ',', '.') AS DECIMAL) AS PORCENTAJEVALORMERCADO,
			CAST(REPLACE(VALORMERCADO, ',', '.') AS DECIMAL) AS VALORMERCADO,
			CAST(REPLACE(VALORPRESENTE, ',', '.') AS DECIMAL) AS VALORPRESENTE,
			CAST(REPLACE(TIPOCAMBIOCOMPRA, ',', '.') AS DECIMAL) AS TIPOCAMBIOCOMPRA,
			CAST(REPLACE(TIPOCAMBIOCIERRE, ',', '.') AS DECIMAL) AS TIPOCAMBIOCIERRE,
			CAST(REPLACE(GANOPERDIFCAMBIARIO, ',', '.') AS DECIMAL) AS GANOPERDIFCAMBIARIO,
			CAST(REPLACE(GANOPERDNOREALIZADA, ',', '.') AS DECIMAL) AS GANOPERDNOREALIZADA,
			CAST(REPLACE(PRIMAODESCUENTO, ',', '.') AS DECIMAL) AS PRIMAODESCUENTO,
			CAST(REPLACE(COSTOAMORTIZADO, ',', '.') AS DECIMAL) AS COSTOAMORTIZADO,
			CAST(REPLACE(VALORENLIBROS, ',', '.') AS DECIMAL) AS VALORENLIBROS,
			CAST(REPLACE(TASADESCTO, ',', '.') AS DECIMAL) AS TASADESCTO,
			NROACCIONES AS NROACCIONES,
			CAST(REPLACE(PRECIOMERCADOACCIONES, ',', '.') AS DECIMAL) AS PRECIOMERCADOACCIONES,
			CAST(REPLACE(PARTCPATRIMONIAL, ',', '.') AS DECIMAL) AS PARTCPATRIMONIAL,
			CAST(REPLACE(MONTOPROVISION, ',', '.') AS DECIMAL) AS MONTOPROVISION,
			NRODECRETO AS NRODECRETO,
			NROEMISION AS NROEMISION,
			SERIEINSTR AS SERIEINSTR,
			CAST(REPLACE(TASAINTCUPON, ',', '.') AS DECIMAL) AS TASAINTCUPON,
			CAST(REPLACE(TASAINTERESES, ',', '.') AS DECIMAL) AS TASAINTERESES,
			FECHAINICIOCP AS FECHAINICIOCP,
			FECHAVTOCP AS FECHAVTOCP,
			CAST(REPLACE(INTERESESCOBRADOS, ',', '.') AS DECIMAL) AS INTERESESCOBRADOS,
			CAST(REPLACE(INTERESESDEVENGADOS, ',', '.') AS DECIMAL) AS INTERESESDEVENGADOS,
			CAST(REPLACE(DIVIDENDOSCOBRADOS, ',', '.') AS DECIMAL) AS DIVIDENDOSCOBRADOS,
			CAST(REPLACE(RENDPORCOBRAR, ',', '.') AS DECIMAL) AS RENDPORCOBRAR,
			PERIOPAGOINT AS PERIOPAGOINT,
			FECHACOBRO AS FECHACOBRO,
			CAST(REPLACE(DIVDECRNOCOBRADOS, ',', '.') AS DECIMAL) AS DIVDECRNOCOBRADOS,
			CTACBLEORITRANS AS CTACBLEORITRANS,
			CAST(REPLACE(MONTOCANJE, ',', '.') AS DECIMAL) AS MONTOCANJE,
			FECHACANJE AS FECHACANJE,
			CONTRAPARTECANJE AS CONTRAPARTECANJE,
			CODINSTRENTREGADO AS CODINSTRENTREGADO,
			CAST(REPLACE(PATRIEMPRESA, ',', '.') AS DECIMAL) AS PATRIEMPRESA,
			FECHAEDOFINANCIERO AS FECHAEDOFINANCIERO,
			CAST(REPLACE(MONTOCAPSOCIAL, ',', '.') AS DECIMAL) AS MONTOCAPSOCIAL,
			CAST(REPLACE(NROACCIONESCIRC, ',', '.') AS DECIMAL) AS NROACCIONESCIRC,
			CAST(CANTIDADACCIONES AS NUMERIC) AS CANTIDADACCIONES,
			CAST(ACTIVOSUBYACENTE AS NUMERIC) AS ACTIVOSUBYACENTE,
			CAST(REPLACE(VALORNOMACTIVO, ',', '.') AS DECIMAL) AS VALORNOMACTIVO,
			MONEDAACTIVO AS MONEDAACTIVO,
			CAST(REPLACE(TIPOCAMCIERRESUB, ',', '.') AS DECIMAL) AS TIPOCAMCIERRESUB,
			CODEMISORSUB AS CODEMISORSUB,
			CODCUSTODIOSUB AS CODCUSTODIOSUB,
			CAST(REPLACE(TASACUPONSUB, ',', '.') AS DECIMAL) AS TASACUPONSUB,
			FECHAVCTOSUB AS FECHAVCTOSUB,
			CAST(REPLACE(RESULTADONETO, ',', '.') AS DECIMAL) AS RESULTADONETO,
			CAST(REPLACE(GANOPERPARTPATRIM, ',', '.') AS DECIMAL) AS GANOPERPARTPATRIM,
			TRIM(BASECALCULO) AS BASECALCULO,
			'LA' AS PORCION
        FROM temp_at10_union_la;
    """
    hook.copy_expert(sql=temp_sql, filename=local_file_path_la)
    os.remove(local_file_path_la)
    os.rmdir(temp_dir)



###### DEFINICION DEL DAG ######

default_args = {
    'owner': 'airflow',
    'start_date': datetime(2024, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(dag_id='AT10',
          default_args=default_args,
          schedule=None, # Aqui se programa cada cuanto ejecutar el DAG
          catchup=False,
          tags=['ATs', 'AT10','Unificado'])

FileAT_task = PythonOperator(
    task_id='FileAT_task',
    python_callable=FileAT,
    dag=dag
)

FileCodSupervisado_task = PythonOperator(
    task_id='FileCodSupervisado_task',
    python_callable=FileCodSupervisado,
    dag=dag
)

FechaFile_task = PythonOperator(
    task_id='FechaFile_task',
    python_callable=FechaFile,
    dag=dag
)

AT10_FileName_LA_task = PythonOperator(
    task_id='AT10_FileName_LA_task',
    python_callable=AT10_FileName_LA,
    dag=dag
)

AT10_FileName_Fideicomiso_task = PythonOperator(
    task_id='AT10_FileName_Fideicomiso_task',
    python_callable=AT10_FileName_Fideicomiso,
    dag=dag
)

AT10_UNION_task = PythonOperator(
    task_id='AT10_UNION_task',
    python_callable=AT10_UNION,
    dag=dag
)

###### SECUENCIA DE EJECUCION ######
FileAT_task >> FileCodSupervisado_task >> FechaFile_task >> AT10_FileName_LA_task >> AT10_FileName_Fideicomiso_task >> AT10_UNION_task
