from airflow import DAG
from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.providers.postgres.hooks.postgres import PostgresHook
from airflow.models import Variable
from airflow.operators.trigger_dagrun import TriggerDagRunOperator
from airflow.sensors.filesystem import FileSensor
from airflow.sensors.base import BaseSensorOperator
from datetime import datetime, timedelta
import logging
from decimal import Decimal
import json
import time
import os
import tempfile
from airflow.providers.google.cloud.hooks.gcs import GCSHook



logger = logging.getLogger(__name__)

def serialize_value(value):
    """
    Helper para serializar valores de PostgreSQL a JSON.
    Convierte Decimal, date, datetime a string para preservar precisión.
    """
    if value is None:
        return ""
    if isinstance(value, str):
        return value  # Ya es string
    if isinstance(value, datetime):
        return value.isoformat()  # Formato ISO 8601
    if isinstance(value, (int, float, Decimal)):
        return str(value)  # Tipos numericos
    return json.dumps(value)  # Otros tipos

def get_variable(key, default_var=""):
    """
    Helper para obtener variables de Airflow y deserializarlas.
    Retorna el valor como string (compatible con SQL queries).
    
    Para conversiones específicas:
    - int: int(get_variable('key'))
    - Decimal: Decimal(get_variable('key'))
    - datetime: datetime.fromisoformat(get_variable('key'))
    """
    raw = Variable.get(key, default_var=default_var)
    try:
        return json.loads(raw)
    except Exception:
        return raw
### FUNCIONES DE CADA TAREA ###

def FileName(**kwargs):
    value = '_FIDEICOMISO'
    Variable.set('FileName', serialize_value(value))

def AT10_FIDEICOMISO_TOFILE(**kwargs):

    #Inicializa los hooks
    hook = PostgresHook(postgres_conn_id='repodataprd')
    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')

    # Se hace drop de la tabla si existe
    hook.run("DROP TABLE IF EXISTS ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO;")

    # Crea tabla para ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO si no existe
    hook.run('''
        CREATE TABLE IF NOT EXISTS ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO (
        OFICINA VARCHAR(10),
        CODINSTRUMENTO VARCHAR(20),
        TIPOSISTEMA VARCHAR(10),
        CODCTACONTABLE VARCHAR(20),
        IDINSTRUMENTO VARCHAR(10),
        CODEMISOR VARCHAR(10),
        PAISEMISOR VARCHAR(10),
        CODCUSTODIO VARCHAR(10),
        PAISCUSTODIO VARCHAR(10),
        EMPRESARIESGOCUSTODIO VARCHAR(200),
        CALIFRIESGOCUSTODIO VARCHAR(20),
        MONEDA VARCHAR(10),
        FECHAEMISION VARCHAR(8),
        FECHAADQUISICION VARCHAR(8),
        FECHAVCTO VARCHAR(8),
        ULTFECHATRANS VARCHAR(8),
        NROTRANSFERENCIAS VARCHAR(100),
        VALORNOMINAL VARCHAR(50),
        COSTOADQUISICION VARCHAR(50),
        VALORMERCADOTRANS VARCHAR(50),
        PORCENTAJECOMPRA VARCHAR(50),
        PORCENTAJEVALORMERCADO VARCHAR(50),
        VALORMERCADO VARCHAR(50),
        VALORPRESENTE VARCHAR(50),
        TIPOCAMBIOCOMPRA VARCHAR(50),
        TIPOCAMBIOCIERRE VARCHAR(50),
        GANOPERDIFCAMBIARIO VARCHAR(50),
        GANOPERDNOREALIZADA VARCHAR(50),
        PRIMAODESCUENTO VARCHAR(50),
        COSTOAMORTIZADO VARCHAR(50),
        VALORENLIBROS VARCHAR(50),
        TASADESCTO VARCHAR(50),
        NROACCIONES VARCHAR(30),
        PRECIOMERCADOACCIONES VARCHAR(50),
        PARTCPATRIMONIAL VARCHAR(50),
        MONTOPROVISION VARCHAR(50),
        NRODECRETO VARCHAR(100),
        NROEMISION VARCHAR(100),
        SERIEINSTR VARCHAR(100),
        TASAINTCUPON VARCHAR(50),
        TASAINTERESES VARCHAR(50),
        FECHAINICIOCP VARCHAR(8),
        FECHAVTOCP VARCHAR(8),
        INTERESESCOBRADOS VARCHAR(50),
        INTERESESDEVENGADOS VARCHAR(50),
        DIVIDENDOSCOBRADOS VARCHAR(50),
        RENDPORCOBRAR VARCHAR(50),
        PERIOPAGOINT VARCHAR(30),
        FECHACOBRO VARCHAR(8),
        DIVDECRNOCOBRADOS VARCHAR(50),
        CTACBLEORITRANS VARCHAR(30),
        MONTOCANJE VARCHAR(50),
        FECHACANJE VARCHAR(8),
        CONTRAPARTECANJE VARCHAR(100),
        CODINSTRENTREGADO VARCHAR(15),
        PATRIEMPRESA VARCHAR(50),
        FECHAEDOFINANCIERO VARCHAR(8),
        MONTOCAPSOCIAL VARCHAR(50),
        NROACCIONESCIRC VARCHAR(50),
        CANTIDADACCIONES VARCHAR(50),
        ACTIVOSUBYACENTE VARCHAR(50),
        VALORNOMACTIVO VARCHAR(50),
        MONEDAACTIVO VARCHAR(10),
        TIPOCAMCIERRESUB VARCHAR(50),
        CODEMISORSUB VARCHAR(10),
        CODCUSTODIOSUB VARCHAR(10),
        TASACUPONSUB VARCHAR(50),
        FECHAVCTOSUB VARCHAR(8),
        RESULTADONETO VARCHAR(50),
        GANOPERPARTPATRIM VARCHAR(50),
        BASECALCULO VARCHAR(30)
    );
    ''')

    # Vaciamos la tabla para no duplicar datos.
    hook.run("TRUNCATE TABLE ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO;")

	# Crea tabla temporal y guarda data
    hook.run('''
        INSERT INTO ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO (
		OFICINA,
		CODINSTRUMENTO,
		TIPOSISTEMA,
		CODCTACONTABLE,
		IDINSTRUMENTO,
		CODEMISOR,
		PAISEMISOR,
		CODCUSTODIO,
		PAISCUSTODIO,
		EMPRESARIESGOCUSTODIO,
		CALIFRIESGOCUSTODIO,
		MONEDA,
		FECHAEMISION,
		FECHAADQUISICION,
		FECHAVCTO,
		ULTFECHATRANS,
		NROTRANSFERENCIAS,
		VALORNOMINAL,
		COSTOADQUISICION,
		VALORMERCADOTRANS,
		PORCENTAJECOMPRA,
		PORCENTAJEVALORMERCADO,
		VALORMERCADO,
		VALORPRESENTE,
		TIPOCAMBIOCOMPRA,
		TIPOCAMBIOCIERRE,
		GANOPERDIFCAMBIARIO,
		GANOPERDNOREALIZADA,
		PRIMAODESCUENTO,
		COSTOAMORTIZADO,
		VALORENLIBROS,
		TASADESCTO,
		NROACCIONES,
		PRECIOMERCADOACCIONES,
		PARTCPATRIMONIAL,
		MONTOPROVISION,
		NRODECRETO,
		NROEMISION,
		SERIEINSTR,
		TASAINTCUPON,
		TASAINTERESES,
		FECHAINICIOCP,
		FECHAVTOCP,
		INTERESESCOBRADOS,
		INTERESESDEVENGADOS,
		DIVIDENDOSCOBRADOS,
		RENDPORCOBRAR,
		PERIOPAGOINT,
		FECHACOBRO,
		DIVDECRNOCOBRADOS,
		CTACBLEORITRANS,
		MONTOCANJE,
		FECHACANJE,
		CONTRAPARTECANJE,
		CODINSTRENTREGADO,
		PATRIEMPRESA,
		FECHAEDOFINANCIERO,
		MONTOCAPSOCIAL,
		NROACCIONESCIRC,
		CANTIDADACCIONES,
		ACTIVOSUBYACENTE,
		VALORNOMACTIVO,
		MONEDAACTIVO,
		TIPOCAMCIERRESUB,
		CODEMISORSUB,
		CODCUSTODIOSUB,
		TASACUPONSUB,
		FECHAVCTOSUB,
		RESULTADONETO,
		GANOPERPARTPATRIM,
		BASECALCULO
	)
    SELECT 
        AT10_FIDEICOMISO_FINAL.OFICINA AS OFICINA,
        AT10_FIDEICOMISO_FINAL.CODINSTRUMENTO AS CODINSTRUMENTO,
        AT10_FIDEICOMISO_FINAL.TIPOSISTEMA AS TIPOSISTEMA,
        AT10_FIDEICOMISO_FINAL.CODCTACONTABLE AS CODCTACONTABLE,
        AT10_FIDEICOMISO_FINAL.IDINSTRUMENTO AS IDINSTRUMENTO,
        AT10_FIDEICOMISO_FINAL.CODEMISOR AS CODEMISOR,
        AT10_FIDEICOMISO_FINAL.PAISEMISOR AS PAISEMISOR,
        AT10_FIDEICOMISO_FINAL.CODCUSTODIO AS CODCUSTODIO,
        AT10_FIDEICOMISO_FINAL.PAISCUSTODIO AS PAISCUSTODIO,
        AT10_FIDEICOMISO_FINAL.EMPRESARIESGOCUSTODIO AS EMPRESARIESGOCUSTODIO,
        AT10_FIDEICOMISO_FINAL.CALIFRIESGOCUSTODIO AS CALIFRIESGOCUSTODIO,
        AT10_FIDEICOMISO_FINAL.MONEDA AS MONEDA,
        AT10_FIDEICOMISO_FINAL.FECHAEMISION AS FECHAEMISION,
        AT10_FIDEICOMISO_FINAL.FECHAADQUISICION AS FECHAADQUISICION,
        AT10_FIDEICOMISO_FINAL.FECHAVCTO AS FECHAVCTO,
        AT10_FIDEICOMISO_FINAL.ULTFECHATRANS AS ULTFECHATRANS,
        AT10_FIDEICOMISO_FINAL.NROTRANSFERENCIAS AS NROTRANSFERENCIAS,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.VALORNOMINAL = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.VALORNOMINAL, 'FM99999999999990D00'),'.',',')) 
        END AS VALORNOMINAL,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.COSTOADQUISICION = 0 THEN '0,00' 
            WHEN (AT10_FIDEICOMISO_FINAL.CODINSTRUMENTO IN ('USP97475AG56') AND AT10_FIDEICOMISO_FINAL.FECHAADQUISICION = '20191128') THEN TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, 'FM99999999999990D0000'),'.',',')) 
            WHEN (AT10_FIDEICOMISO_FINAL.CODINSTRUMENTO IN ('USP97475AG56') AND AT10_FIDEICOMISO_FINAL.VALORNOMINAL = 62000) THEN TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, 'FM99999999999990D0000'),'.',',')) 
            WHEN (CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PRIMAODESCUENTO, 'FM999999999990D99'), ',', '.') AS NUMERIC) - ((CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, 'FM999999999990D99'), ',', '.') AS NUMERIC) - AT10_FIDEICOMISO_FINAL.VALORNOMINAL) * AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCIERRE)) > 50 OR (CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PRIMAODESCUENTO, '999999999990D99'), ',', '.') AS NUMERIC) - ((CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, '999999999990D99'), ',', '.') AS NUMERIC) - AT10_FIDEICOMISO_FINAL.VALORNOMINAL) * AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCIERRE)) < -50 THEN TRIM(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, '99999999999990D9999')) 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, 'FM99999999999990D00'),'.',',')) 
        END AS COSTOADQUISICION,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.VALORMERCADOTRANS = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.VALORMERCADOTRANS, 'FM99999999999990D00'),'.',',')) 
        END AS VALORMERCADOTRANS,
        CASE 
            WHEN (CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PRIMAODESCUENTO, 'FM99999999999990D99'), ',', '.') AS NUMERIC) - ((CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, '99999999999990D99'), ',', '.') AS NUMERIC) - AT10_FIDEICOMISO_FINAL.VALORNOMINAL) * AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCIERRE)) > 50 OR (CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PRIMAODESCUENTO, '99999999999990D99'), ',', '.') AS NUMERIC) - ((CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, '99999999999990D99'), ',', '.') AS NUMERIC) - AT10_FIDEICOMISO_FINAL.VALORNOMINAL) * AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCIERRE)) < -50 THEN REPLACE(TO_CHAR(ROUND(((CAST(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOADQUISICION, '99999999999990D9999'), ',', '.') AS NUMERIC) / AT10_FIDEICOMISO_FINAL.VALORNOMINAL) * 100), 8), '99999999999990D00000000'),'.',',') 
            WHEN AT10_FIDEICOMISO_FINAL.PORCENTAJECOMPRA = 0 THEN '0,00000000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PORCENTAJECOMPRA, 'FM99999999999990D00000000'),'.',',')) 
        END AS PORCENTAJECOMPRA,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.PORCENTAJEVALORMERCADO = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PORCENTAJEVALORMERCADO, 'FM99999999999990D0000'),'.',',')) 
        END AS PORCENTAJEVALORMERCADO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.VALORMERCADO = 0 THEN '0,00000000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.VALORMERCADO, 'FM99999999999990D00000000'),'.',',')) 
        END AS VALORMERCADO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.VALORPRESENTE = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.VALORPRESENTE, 'FM99999999999990D00'),'.',',')) 
        END AS VALORPRESENTE,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCOMPRA = 0 THEN '0,00000000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCOMPRA, 'FM99999999999990D00000000'),'.',',')) 
        END AS TIPOCAMBIOCOMPRA,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCIERRE = 0 THEN '0,00000000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TIPOCAMBIOCIERRE, 'FM99999999999990D00000000'),'.',',')) 
        END AS TIPOCAMBIOCIERRE,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.GANOPERDIFCAMBIARIO = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.GANOPERDIFCAMBIARIO, 'FM99999999999990D00'),'.',',')) 
        END AS GANOPERDIFCAMBIARIO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.GANOPERDNOREALIZADA = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.GANOPERDNOREALIZADA, 'FM99999999999990D00'),'.',',')) 
        END AS GANOPERDNOREALIZADA,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.PRIMAODESCUENTO = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PRIMAODESCUENTO, 'FM99999999999990D00'),'.',',')) 
        END AS PRIMAODESCUENTO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.COSTOAMORTIZADO = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.COSTOAMORTIZADO, 'FM99999999999990D00'),'.',',')) 
        END AS COSTOAMORTIZADO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.VALORENLIBROS = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.VALORENLIBROS, 'FM99999999999990D00'),'.',',')) 
        END AS VALORENLIBROS,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TASADESCTO = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TASADESCTO, 'FM99999999999990D0000'),'.',',')) 
        END AS TASADESCTO,
        AT10_FIDEICOMISO_FINAL.NROACCIONES AS NROACCIONES,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.PRECIOMERCADOACCIONES = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PRECIOMERCADOACCIONES, 'FM99999999999990D00'),'.',',')) 
        END AS PRECIOMERCADOACCIONES,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.PARTCPATRIMONIAL = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PARTCPATRIMONIAL, 'FM99999999999990D0000'),'.',',')) 
        END AS PARTCPATRIMONIAL,
        CASE 
            WHEN (AT10_FIDEICOMISO_FINAL.MONTOPROVISION = 0 OR AT10_FIDEICOMISO_FINAL.MONTOPROVISION IS NULL) THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.MONTOPROVISION, 'FM99999999999990D00'),'.',',')) 
        END AS MONTOPROVISION,
        AT10_FIDEICOMISO_FINAL.NRODECRETO AS NRODECRETO,
        LPAD(AT10_FIDEICOMISO_FINAL.NROEMISION::TEXT, 4, '0') AS NROEMISION,
        LPAD(AT10_FIDEICOMISO_FINAL.SERIEINSTR::TEXT, 6, '0') AS SERIEINSTR,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TASAINTCUPON = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TASAINTCUPON, 'FM99999999999990D0000'),'.',',')) 
        END AS TASAINTCUPON,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TASAINTERESES = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TASAINTERESES, 'FM99999999999990D0000'),'.',',')) 
        END AS TASAINTERESES,
        AT10_FIDEICOMISO_FINAL.FECHAINICIOCP AS FECHAINICIOCP,
        AT10_FIDEICOMISO_FINAL.FECHAVTOCP AS FECHAVTOCP,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.INTERESESCOBRADOS = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.INTERESESCOBRADOS, 'FM99999999999990D00'),'.',',')) 
        END AS INTERESESCOBRADOS,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.INTERESESDEVENGADOS = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.INTERESESDEVENGADOS, 'FM99999999999990D00'),'.',',')) 
        END AS INTERESESDEVENGADOS,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.DIVIDENDOSCOBRADOS = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.DIVIDENDOSCOBRADOS, 'FM99999999999990D00'),'.',',')) 
        END AS DIVIDENDOSCOBRADOS,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.RENDPORCOBRAR = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.RENDPORCOBRAR, 'FM99999999999990D00'),'.',',')) 
        END AS RENDPORCOBRAR,
        AT10_FIDEICOMISO_FINAL.PERIOPAGOINT AS PERIOPAGOINT,
        AT10_FIDEICOMISO_FINAL.FECHACOBRO AS FECHACOBRO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.DIVDECRNOCOBRADOS = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.DIVDECRNOCOBRADOS, 'FM99999999999990D00'),'.',',')) 
        END AS DIVDECRNOCOBRADOS,
        AT10_FIDEICOMISO_FINAL.CTACBLEORITRANS AS CTACBLEORITRANS,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.MONTOCANJE = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.MONTOCANJE, 'FM99999999999990D00'),'.',',')) 
        END AS MONTOCANJE,
        AT10_FIDEICOMISO_FINAL.FECHACANJE AS FECHACANJE,
        AT10_FIDEICOMISO_FINAL.CONTRAPARTECANJE AS CONTRAPARTECANJE,
        AT10_FIDEICOMISO_FINAL.CODINSTRENTREGADO AS CODINSTRENTREGADO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.PATRIEMPRESA = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.PATRIEMPRESA, 'FM99999999999990D00'),'.',',')) 
        END AS PATRIEMPRESA,
        AT10_FIDEICOMISO_FINAL.FECHAEDOFINANCIERO AS FECHAEDOFINANCIERO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.MONTOCAPSOCIAL = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.MONTOCAPSOCIAL, 'FM99999999999990D00'),'.',',')) 
        END AS MONTOCAPSOCIAL,
        CAST(AT10_FIDEICOMISO_FINAL.NROACCIONESCIRC AS INT) AS NROACCIONESCIRC,
        REPLACE(AT10_FIDEICOMISO_FINAL.CANTIDADACCIONES::TEXT, '.', ',') AS CANTIDADACCIONES,
        REPLACE(AT10_FIDEICOMISO_FINAL.ACTIVOSUBYACENTE::TEXT, '.', ',') AS ACTIVOSUBYACENTE,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.VALORNOMACTIVO = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.VALORNOMACTIVO, 'FM99999999999990D00'),'.',',')) 
        END AS VALORNOMACTIVO,
        CASE
             WHEN AT10_FIDEICOMISO_FINAL.MONEDAACTIVO = '' THEN '0'
             ELSE COALESCE(AT10_FIDEICOMISO_FINAL.MONEDAACTIVO,'0')
        END AS MONEDAACTIVO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TIPOCAMCIERRESUB = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TIPOCAMCIERRESUB, 'FM99999999999990D0000'),'.',',')) 
        END AS TIPOCAMCIERRESUB,
        CASE
             WHEN AT10_FIDEICOMISO_FINAL.CODEMISORSUB = '' THEN '0'
             ELSE COALESCE(AT10_FIDEICOMISO_FINAL.CODEMISORSUB,'0')
        END AS CODEMISORSUB,
        CASE
             WHEN AT10_FIDEICOMISO_FINAL.CODCUSTODIOSUB = '' THEN '0'
             ELSE COALESCE(AT10_FIDEICOMISO_FINAL.CODCUSTODIOSUB,'0')
        END AS CODCUSTODIOSUB,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.TASACUPONSUB = 0 THEN '0,0000' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.TASACUPONSUB, 'FM99999999999990D0000'),'.',',')) 
        END AS TASACUPONSUB,
        AT10_FIDEICOMISO_FINAL.FECHAVCTOSUB AS FECHAVCTOSUB,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.RESULTADONETO = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.RESULTADONETO, 'FM99999999999990D00'),'.',',')) 
        END AS RESULTADONETO,
        CASE 
            WHEN AT10_FIDEICOMISO_FINAL.GANOPERPARTPATRIM = 0 THEN '0,00' 
            ELSE TRIM(REPLACE(TO_CHAR(AT10_FIDEICOMISO_FINAL.GANOPERPARTPATRIM, 'FM99999999999990D00'),'.',',')) 
        END AS GANOPERPARTPATRIM,
        AT10_FIDEICOMISO_FINAL.BASECALCULO AS BASECALCULO
    FROM AT_STG.AT10_FIDEICOMISO_FINAL
    ORDER BY CAST(CODCTACONTABLE AS NUMERIC), VALORNOMINAL;
    ''')


def ATS_TH_ATnumero_TOTXT(**kwargs):

    #Inicializa los hooks
    hook = PostgresHook(postgres_conn_id='repodataprd')
    gcs_hook = GCSHook(gcp_conn_id='google_cloud_default')

    # Recuperar las variables definidas en las tareas previas
    AT10_FileName_Fideicomiso = get_variable("AT10_FileName_Fideicomiso", default_var="_FIDEICOMISO")
    FileAT = get_variable("FileAT", default_var="AT10")
    FileCodSupervisado = get_variable('FileCodSupervisado')
    FechaFile = get_variable('FechaFile')

    # Generar txt desde la base de datos
    logger.info("Obteniendo registros de la base de datos...")
    #registros = hook.get_records("SELECT * FROM ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO ORDER BY CAST(CODCTACONTABLE AS NUMERIC), VALORNOMINAL;")
    query_string = '''
        SELECT 
            OFICINA, CODINSTRUMENTO, TIPOSISTEMA, CODCTACONTABLE, IDINSTRUMENTO, CODEMISOR, PAISEMISOR, CODCUSTODIO, PAISCUSTODIO, EMPRESARIESGOCUSTODIO,
            CALIFRIESGOCUSTODIO, MONEDA, FECHAEMISION, FECHAADQUISICION, FECHAVCTO, ULTFECHATRANS, NROTRANSFERENCIAS,
            REPLACE(VALORNOMINAL,'.',',') AS VALORNOMINAL,
            REPLACE(COSTOADQUISICION,'.',',') AS COSTOADQUISICION,
            REPLACE(VALORMERCADOTRANS,'.',',') AS VALORMERCADOTRANS,
            REPLACE(PORCENTAJECOMPRA,'.',',') AS PORCENTAJECOMPRA,
            REPLACE(PORCENTAJEVALORMERCADO,'.',',') AS PORCENTAJEVALORMERCADO,
            REPLACE(VALORMERCADO,'.',',') AS VALORMERCADO,
            REPLACE(VALORPRESENTE,'.',',') AS VALORPRESENTE,
            REPLACE(TIPOCAMBIOCOMPRA,'.',',') AS TIPOCAMBIOCOMPRA,
            REPLACE(TIPOCAMBIOCIERRE,'.',',') AS TIPOCAMBIOCIERRE,
            REPLACE(GANOPERDIFCAMBIARIO,'.',',') AS GANOPERDIFCAMBIARIO,
            REPLACE(GANOPERDNOREALIZADA,'.',',') AS GANOPERDNOREALIZADA,
            REPLACE(PRIMAODESCUENTO,'.',',') AS PRIMAODESCUENTO,
            REPLACE(COSTOAMORTIZADO,'.',',') AS COSTOAMORTIZADO,
            REPLACE(VALORENLIBROS,'.',',') AS VALORENLIBROS,
            REPLACE(TASADESCTO,'.',',') AS TASADESCTO,
            NROACCIONES,
            REPLACE(PRECIOMERCADOACCIONES,'.',',') AS PRECIOMERCADOACCIONES,
            REPLACE(PARTCPATRIMONIAL,'.',',') AS PARTCPATRIMONIAL,
            REPLACE(MONTOPROVISION,'.',',') AS MONTOPROVISION,
            NRODECRETO, LPAD(NROEMISION, 4, '0') AS NROEMISION, LPAD(SERIEINSTR, 6, '0') AS SERIEINSTR,
            REPLACE(TASAINTCUPON,'.',',') AS TASAINTCUPON,
            REPLACE(TASAINTERESES,'.',',') AS TASAINTERESES,
            FECHAINICIOCP, FECHAVTOCP,
            REPLACE(INTERESESCOBRADOS,'.',',') AS INTERESESCOBRADOS,
            REPLACE(INTERESESDEVENGADOS,'.',',') AS INTERESESDEVENGADOS,
            REPLACE(DIVIDENDOSCOBRADOS,'.',',') AS DIVIDENDOSCOBRADOS,
            REPLACE(RENDPORCOBRAR,'.',',') AS RENDPORCOBRAR,
            PERIOPAGOINT, FECHACOBRO,
            REPLACE(DIVDECRNOCOBRADOS,'.',',') AS DIVDECRNOCOBRADOS,
            CTACBLEORITRANS,
            REPLACE(MONTOCANJE,'.',',') AS MONTOCANJE,
            FECHACANJE, CONTRAPARTECANJE, CODINSTRENTREGADO,
            REPLACE(PATRIEMPRESA,'.',',') AS PATRIEMPRESA,
            FECHAEDOFINANCIERO,
            REPLACE(MONTOCAPSOCIAL,'.',',') AS MONTOCAPSOCIAL,
            NROACCIONESCIRC AS NROACCIONESCIRC,
            CANTIDADACCIONES AS CANTIDADACCIONES,
            ACTIVOSUBYACENTE AS ACTIVOSUBYACENTE,
            REPLACE(VALORNOMACTIVO,'.',',') AS VALORNOMACTIVO,
            MONEDAACTIVO,
            REPLACE(TIPOCAMCIERRESUB,'.',',') AS TIPOCAMCIERRESUB,
            CODEMISORSUB, CODCUSTODIOSUB,
            REPLACE(TASACUPONSUB,'.',',') AS TASACUPONSUB,
            FECHAVCTOSUB,
            REPLACE(RESULTADONETO,'.',',') AS RESULTADONETO,
            REPLACE(GANOPERPARTPATRIM,'.',',') AS GANOPERPARTPATRIM,
            BASECALCULO
        FROM ATSUDEBAN.ATS_TH_AT10_FIDEICOMISO ORDER BY CAST(CODCTACONTABLE AS NUMERIC), VALORNOMINAL
    '''
    registros = hook.get_records(query_string)
    logger.info(f"Se obtuvieron {len(registros)} registros.")

    # Definir la ruta del archivo de salida en GCS
    gcs_bucket = 'airflow-dags-data'
    gcs_object_path = f"data/AT10/SALIDAS/{FileAT}{FileCodSupervisado}{FechaFile}_FIDEICOMISO.txt"

    temp_dir = tempfile.mkdtemp() # Crea un directorio temporal
    local_file_path = os.path.join(temp_dir, f"{FileAT}{FileCodSupervisado}{FechaFile}.txt") # Ruta del archivo temporal local

    try:
        logger.info(f"Escribiendo datos a archivo temporal local: {local_file_path}")
        # Escribir los registros en el archivo de texto temporal local
        with open(local_file_path, 'w', encoding='utf-8') as f:
            for row in registros:
                # Convertimos cada fila (tupla) a una cadena separada por tildes y aseguramos que los valores None se traten como cadenas vaci­as
                linea = "~".join(str(valor) if valor is not None else "" for valor in row)
                f.write(linea + "\n")

        logger.info(f"Archivo temporal local generado correctamente. Subiendo a GCS: gs://{gcs_bucket}/{gcs_object_path}")

        # Subir el archivo temporal local a GCS
        gcs_hook.upload(
            bucket_name=gcs_bucket,
            object_name=gcs_object_path,
            filename=local_file_path,
            #mime_type='text/plain' # Opcional: especificar el tipo MIME
        )
        logger.info(f"Archivo generado y subido a GCS: gs://{gcs_bucket}/{gcs_object_path}")

    except Exception as e:
        logger.error(f"Error durante la generacion o subida del archivo: {str(e)}")
        import traceback
        logger.error("Traceback completo:\n" + traceback.format_exc())
        raise

    finally:
        # Limpieza: Asegurarse de eliminar el archivo temporal y el directorio
        if os.path.exists(local_file_path):
            os.remove(local_file_path)
            logger.info(f"Archivo temporal eliminado: {local_file_path}")
        if os.path.exists(temp_dir):
            os.rmdir(temp_dir)
            logger.info(f"Directorio temporal eliminado: {temp_dir}")


###### DEFINICION DEL DAG ######

default_args = {
    'owner': 'airflow',
    'start_date': datetime(2024, 1, 1),
    'retries': 1,
    'retry_delay': timedelta(minutes=5)
}

dag = DAG(dag_id='AT10_FIDEICOMISO_TOFILE',
          default_args=default_args,
          schedule=None, # Aqui se programa cada cuanto ejecutar el DAG
          catchup=False,
          tags=['ATs', 'AT10','Fideicomiso','To_File'])

FileName_task = PythonOperator(
    task_id='FileName_task',
    python_callable=FileName,
    dag=dag
)

AT10_FIDEICOMISO_TOFILE_task = PythonOperator(
    task_id='AT10_FIDEICOMISO_TOFILE_task',
    python_callable=AT10_FIDEICOMISO_TOFILE,
    dag=dag
)

ATS_TH_ATnumero_TOTXT_task = PythonOperator(
    task_id='ATS_TH_ATnumero_TOTXT_task',
    python_callable=ATS_TH_ATnumero_TOTXT,
    dag=dag
)

def enviar_correo_task_callable(**kwargs):
    """Envía email usando send_email() - Convertido desde EmailOperator"""
    from airflow.utils.email import send_email
    send_email(
        to="daniel.figueroa@kreadata.com",
        subject="AT10 PORCIÓN FIDEICOMISO - ARCHIVOS DE TRANSMISION (SIIF) DWH EN LA NUBE GCP (Airflow) - GALIPÁN TECNOLOGICO",
        html_content="""

        <h3>¡Buen día!</h3>
        <p>Se ha generado de forma automática <b>'la porción de FIDEICOMISO del AT10'</b>, el mismo se encuentra en la ruta 'data/AT10/SALIDAS' del bucket. El nombre del reporte es: {{ var.value.FileAT }}{{ var.value.FileCodSupervisado }}{{ var.value.FechaFile }}_FIDEICOMISO.txt</p>
    
        """
    )

enviar_correo_task = PythonOperator(
    task_id="enviar_correo",
    python_callable=enviar_correo_task_callable,
    dag=dag
)

###### SECUENCIA DE EJECUCION ######
FileName_task >> AT10_FIDEICOMISO_TOFILE_task >> ATS_TH_ATnumero_TOTXT_task >> enviar_correo_task
